name: Pull Salesforce Metadata 12

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global
      - name: Install Code Analyzer Plugin
        run: sfdx plugins:install @salesforce/sfdx-scanner
      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "myTemporaryFile.pem"
          encodedString: ${{ vars.SF_PRIVATE_KEY }}
      - name: Authenticate with Salesforce using JWT Token
        env:
          SF_CLIENT_ID: ${{ vars.SF_CLIENT_ID }}
          SF_PRIVATE_KEY: ${{ steps.write_file.outputs.filePath }}
          SF_USERNAME: ${{ vars.SF_USERNAME }}
        run: sfdx force:auth:jwt:grant --clientid $SF_CLIENT_ID --jwtkeyfile $SF_PRIVATE_KEY --username $SF_USERNAME --setdefaultdevhubusername --setalias my-org
      - name: Run Code Analyzer
        run: sfdx scanner:run --target "*/**/*.cls" --outfile "ScannerResult.csv" --severity-threshold 2
        continue-on-error: true
      # - bash: |
      #     echo "##vso[task.setvariable variable=task.RunCodeAnalyzer.status]Success"
      #   displayName: 'RunCodeAnalyzer status'
      #   condition: succeeded()
      #   continueOnError: true
      # - name: Upload Code Scanner result
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: code-coverage-report
      #     path: output/test/code-coverage.html
      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     pathToPublish: '$(Build.ArtifactStagingDirectory)'
      #     artifactName: drop
      - name: Commit and push changes
        run: |
          git config --local user.email "nitin.nayan786@gmail.com"
          git config --local user.name "nkn-boss"
          git add .
          git commit -m "Retrieved metadata from Salesforce"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
